from matplotlib.pylab import sample
import pm4py
import time 
import pandas as pd
import numpy as np
from wakepy import keep
class FileHandler:
    """
    A class for handling data. 
    call pipeline(file_path, output_path, activities_to_value, pos_activities, neg_activities) to read a file, convert it to sequences, label the sequences, and write the labeled sequences to a csv file, using :
    - activities_to_value (dict[str, str]) to specify which activities have associated values in which columns (see explanation below),
    - pos_activities (set[str]) to specify which activities are positive,
    - neg_activities (set[str]) to specify which activities are negative.

    else :
    to recuperate a dataframe from a csv file generated by the pipeline,

    call get_from_file(file_path) to get a dataframe from a file,

    to_sequences makes the dataframe into a list of sequences of events, where each event is a tuple of (activity, other_keys) : other_keys might be empty in the data in which case 0 is default

    Because SAI only wants letters to be (letter, value) pairs,
    to_sequences filters the dataframe so that only on certain activities are other activities included. For example if activities = {'calciumTest': 'Calcium', 'vitamin d': 'Vitamin D'}, then only when activity is calciumTest is the value of column Calcium included as associated value, and when activity is vitamin d is the value of column Vitamin D included as associated value. any other activities stay but without associated value 0.
    """
    def get_from_file(self, file_path):
        start_time = time.time()
        if file_path.endswith('.xes') or file_path.endswith('.xes.gz'):
            log = pm4py.read_xes(file_path)
            dataframe = pm4py.convert_to_dataframe(log)
        elif file_path.endswith('.csv'):
            dataframe = pd.read_csv(file_path)

        else:
            raise ValueError("Unsupported file format. Please provide a .xes, .xes.gz, or .csv file.")
        print(f"got dataframe with {len(dataframe.columns)} columns and {len(dataframe)} rows")
        print(f"head: {dataframe.head()}")
        end_time = time.time()
        print(f"Time taken to read file: {end_time - start_time} seconds")
        return dataframe

    def to_sequences(self, dataframe, key='case:concept:name',activity_key='concept:name', time_key='time:timestamp', activity_to_value:dict[str, str]={}):
        """Convert the dataframe to sequences of events
        events being tuple of (activity, value) : other_keys might be empty in which case 0 is default.
        Also gives a set of unique activities
        activity_to_value is a dictionary mapping activities to the COLUMN in which we get the associated value. For example if activities_to_value = {'calciumTest': 'Calcium', 'vitamin d': 'Vitamin D'}, then only when activity is calciumTest is the value of column Calcium included as associated value, and when activity is vitamin d is the value of column Vitamin D included as associated value. any other activities stay but without associated value 0.
        """
        start_time = time.time()
        sequences = []
        unique_activities = set()
        for case_id, group in dataframe.groupby(key):
            sequence = group.sort_values(time_key)[activity_key].tolist()
            # retrieve associated value each time an activity in the dict appears in the right column
            for activity in sequence:
                if activity in activity_to_value:
                    # Get the associated value from the specified column
                    value = group[group[activity_key] == activity].iloc[0][activity_to_value[activity]]
                else:
                    value = 0
                sequence[sequence.index(activity)] = (activity, value)
                unique_activities.add(activity)
            sequences.append(sequence)

        #get some statistics about the sequences
        number_of_sequences = len(sequences)
        total_events = sum(len(seq) for seq in sequences)
        unique_activities_len = len(unique_activities)
        non_zero_values = len([seq for seq in sequences for activity, value in seq if value != 0])  
        stats = {
            "number_of_sequences": number_of_sequences,
            "total_events": total_events,
            "unique_activities_len": unique_activities_len,
            "non_zero_values": non_zero_values
        }
        end_time = time.time()
        print(f"Time taken to convert to sequences: {end_time - start_time} seconds")
        return sequences,unique_activities, stats
    def label_sequences(self, sequences:list[list[tuple[str, int]]], pos_activities, neg_activities):
        """Label sequences as positive or negative based on the presence of activities in pos_activities and neg_activities"""
        labeled_sequences = []
        labeled, pos, neg = 0, 0, 0
        for sequence in sequences:
            label = False
            for activity, value in sequence:
                #if activity in pos_activities, label True, and REMOVE activity from the sequence

                if activity in pos_activities:
                    label = True
                    labeled += 1
                    pos +=1 
                    break
                elif activity in neg_activities:
                    label = False
                    labeled += 1
                    neg +=1 
                    break
            stripped_sequence = [(activity, value) for activity, value in sequence if activity not in pos_activities and activity not in neg_activities]
            labeled_sequences.append((stripped_sequence, label))
        print(f"{len(sequences)-labeled} sequences were not labeled manually (defaulted to false) because they did not contain any of the specified activities.")
        print(f"Positive: {pos}, Negative: {neg}")
        #debugging : check wether any activity in pos_activities or neg_activities is still in any sequence
        for sequence, label in labeled_sequences:
            for activity, value in sequence:
                if activity in pos_activities or activity in neg_activities:
                    print(f"Error: activity {activity} is still in sequence {sequence} after labeling.")
        return labeled_sequences
    def pipeline(self, file_path, output_path, activities_to_value:dict[str, str]={}, pos_activities:set[str]=set(), neg_activities:set[str]=set()):
        """Read a file, convert it to sequences, label the sequences, and write the labeled sequences to a csv file
        first line of the csv file is the set of unique activities, then each line is a sequence and its label (True or False)"""
        data = self.get_from_file(file_path)
        sequences, unique_activities, stats = self.to_sequences(data, activity_to_value=activities_to_value)
        print(f"got {stats['number_of_sequences']} sequences, total of {stats['total_events']} events, with {stats['non_zero_values']} non-zero associated values. {stats['unique_activities_len']} unique activities.\n")
        print (f"unique activities: {unique_activities} \n")
        labeled_sequences = self.label_sequences(sequences, pos_activities=pos_activities, neg_activities=neg_activities)
        #convert labeled_sequences to dataframe
        unique_activities_str = ', '.join(unique_activities)
        labeled_sequences.insert(0, (unique_activities_str, ''))  # Insert unique activities as the first row
        df = pd.DataFrame(labeled_sequences, columns=['sequence', 'label'])
        df.to_csv(output_path, index=False)



    def csv_to_SAI(self, csv_path, learning_sample_size: float = 0.8):
        """Convert a csv file of labeled sequences with first line being the set of unique activities to a set of tuple of (sequence, label) for SAI"""
        df = pd.read_csv(csv_path)
        sequences = set()
        #iterate over the rest of the rows to get the sequences and labels
        for index, row in df.iterrows():
            if index == 0:  # Skip the first row containing unique activities
                unique_activities = set(row['sequence'].split(', '))
                continue
            #convert string of list into a tuple of (activity, value) pairs then return the tuple of (sequence, label)
            sequence_str = row['sequence']
            sequence = tuple(eval(sequence_str))  # Use eval to convert string representation of list to actual list
            label: bool = row['label']
            sequences.add((sequence, label))
        # Split the sequences into learning and testing samples
        samples_list = list(sequences)
        learning_sample = samples_list[:int(learning_sample_size * len(sequences))]
        test_sample = samples_list[int(learning_sample_size * len(sequences)):]
        return set(learning_sample), set(test_sample), unique_activities


def strip_values_from_sequences(sequences):
    """Strip the associated values from the sequences, returning only the activities"""
    stripped_sequences = []
    for sequence, label in sequences:
        stripped_sequence = [activity for activity, value in sequence]
        stripped_sequences.append((stripped_sequence, label))
    return stripped_sequences


def frequency_analysis(sequences, sfa, threshold=0.2, path="./SAITesting/frequency_analysis", file_type="pdf", print_self_loops=False):
    """
    given a set of sequences and a SFA, print the SFA with states colored according to the frequency of the sequences that reach them,only keeping states that are reached by more than threshold% of the sequences.
    """
    if not sequences:
        print("No sequences provided for frequency analysis.")
        return None
    frequency_dict = {state: 0 for state in sfa.states}
    for sequence, _ in sequences:
        if not sequence:
            frequency_dict[sfa.initial_state] += 1
            continue
        sfa.current_state = sfa.initial_state
        for letter in sequence:
            try:
                sfa.step(letter)
            except KeyError:
                break
        
            frequency_dict[sfa.current_state] = frequency_dict.get(sfa.current_state, 0) + 1
    #NORMALIZE frequencies
    total_sequences = len(sequences)
    float_frequency_dict = {state: freq / total_sequences for state, freq in frequency_dict.items()}
    #print the SFA
    from aalpy.utils.FileHandler import _get_node, _wrap_label
    from pydot import Dot, Node, Edge
    from pathlib import Path
    file_type = file_type.lower()
    output_path = Path(path).with_suffix(f".{file_type}")
    def color_for_ratio(ratio):
        ratio = max(0.0, min(1.0, ratio))
        # white -> red
        r = 255
        g = max(int(255 * (1.0 - (1.0 - threshold)*ratio)), 0)
        b = max(int(255 * (1.0 - (1.0 - threshold)*ratio)), 0)
        return f"#{r:02x}{g:02x}{b:02x}"

    active_states = [
        state
        for state in sfa.states
        if (frequency_dict.get(state, 0) / total_sequences) >= threshold
    ]
    print(f"States reached by more than {threshold*100}% of sequences: {len(active_states)} out of {len(sfa.states)}")


    graph = Dot("frequency_analysis", graph_type="digraph")

    # start node
    graph.add_node(Node("__start0", shape="none", label=""))
    graph.add_edge(Edge("__start0", sfa.initial_state.state_id, label=""))

    for state in active_states:
        ratio = frequency_dict.get(state, 0) / total_sequences
        node = _get_node(state, "sfa")
        node.set("style", "filled")
        node.set("fillcolor", color_for_ratio(ratio))
        node.set("fontcolor", "black")
        graph.add_node(node)

    for state in active_states:
        for pred, target in state.transitions:
            if target not in active_states:
                continue
            if target == state and not print_self_loops:
                continue
            graph.add_edge(
                Edge(
                    state.state_id,
                    target.state_id,
                    label=_wrap_label(str(pred)),
                )
            )
    
    try:
        graph.write(path=output_path, format=file_type if file_type != "dot" else "raw")
        print(f"Model saved to {output_path.as_posix()}.")
    except OSError:
        import traceback
        import sys
        traceback.print_exc()
        print(f"Could not write to the file {output_path.as_posix()}.", file=sys.stderr)

    return output_path


if __name__ == "__main__":
    from aalpy.learning_algs.deterministic_passive.SAI import SAI
    
    from aalpy.utils import save_automaton_to_file, visualize_automaton
    from aalpy.base.BooleanAlgebra import IntervalPredicate, LetterIntervalAlgebra, MonotonicAlgebra, Predicate, BooleanAlgebra, IntervalAlgebra, OrPredicate
    import pickle
    with open('./SAITesting/sfa_BPI2017.pkl', 'rb') as f:
        sfa = pickle.load(f)
    print(f"loaded sfa with {len(sfa.states)} states")
    # visualize_automaton(sfa, path='./SAITesting/sfa_BPI2017')
    # quit()
    fh = FileHandler()
    # fh.pipeline('./SAITesting/BPI Challenge 2017.xes.gz', './SAITesting/labeled_sequences_BPI2017.csv', activities_to_value={'A_Create Application': 'case:RequestedAmount', 'O_Create Offer': 'OfferedAmount'}, pos_activities={'A_Pending','O_Accepted'}, neg_activities={'A_Denied','A_Cancelled'})
    sequences, _, activities = fh.csv_to_SAI('./SAITesting/labeled_sequences_BPI2017.csv', learning_sample_size=1)
    print(f"got {len(sequences)} sequences, with {len(activities)} unique activities: {activities}")
    frequency_analysis(sequences, sfa, threshold=0.2, print_self_loops=False)
    

