from aalpy.automata.Sfa import Sfa, SfaState
from aalpy.base.BooleanAlgebra import IntervalPredicate, Predicate, BooleanAlgebra, IntervalAlgebra, OrPredicate
import numpy as np
from aalpy.learning_algs.deterministic_passive.SAI import SAI
from aalpy.utils import save_automaton_to_file, visualize_automaton
from aalpy.automata import Dfa, DfaState
from aalpy.learning_algs import run_RPNI
from test_sai_characteristic import generate_sfa
import time
from pickle import load,dump
from typing import Set, Tuple
import matplotlib.pyplot as plt

def generate_random_sample(sfa: Sfa, num_samples: int, stop_prob: float, mode:int) -> Set:
    """
    Generate a random sample of words accepted or rejected.
    The sample is generated by performing random walks on the SFA. The walk starts from the initial state.
    The walk can stop with a probability of `stop_prob` at each step.
    Mode 0: at each step a transition is chosen uniformly at random among the available transitions.
    Mode 1: at each step a transition is chosen with a probability proportional to the size of the interval of the transition predicate.
    """
    assert mode in [0, 1], "Mode should be either 0 or 1."
    assert 0 < stop_prob <= 1, "stop_prob should be between 0 and 1."
    sample = set()
    for _ in range(num_samples):
        current_state = sfa.initial_state
        word = []
        while True:
            if np.random.rand() < stop_prob:
                break
            if mode == 0:
                # uniform random choice among available transitions
                if not current_state.transitions:
                    break
                predicate, next_state = current_state.transitions[np.random.randint(len(current_state.transitions))]
            elif mode == 1:
                # probability proportional to the size of the interval, and force probability 0.1 for unbounded intervals
                if not current_state.transitions:
                    break
                sizes = [] 
                for pred, _ in current_state.transitions:
                    if isinstance(pred, IntervalPredicate) and pred.is_satisfiable():
                        if pred.lower is None or pred.upper is None:
                            sizes.append(-1)  # unbounded interval
                        else:  
                            sizes.append(pred.upper - pred.lower)
                    elif isinstance(pred, IntervalPredicate):
                        sizes.append(0)  # unsatisfiable interval
                    else:
                        print(f"Warning: non-interval predicate {pred} encountered.")
                        sizes.append(1)
                total_size = sum(size for size in sizes if size > 0)
                if total_size == 0:
                    probabilities = [1 / len(current_state.transitions)] * len(current_state.transitions)
                else:
                    for i in range(len(sizes)):
                        if sizes[i] == -1:  # unbounded interval
                            sizes[i] = 0.1 * total_size
                    
                    probabilities = [size / sum(sizes) for size in sizes]

                id = np.random.choice(len(current_state.transitions), p=probabilities)
                predicate, next_state = current_state.transitions[id]
            next_letter = sfa.algebra.pick_witness_random(predicate)
            if next_letter is None:
                print(f"Warning: could not pick a witness for predicate {predicate}. Skipping this transition.")
                break
            word.append(next_letter)
            current_state = next_state
        sample.add((tuple(word), current_state.is_accepting))
    return sample


def test_random_sampling(nb_states=5,nb_runs=10, nb_samples=1000, learning_part=0.1, stop_prob=0.1, mode=0, print_info=False):
    """
    Generate a random sample from an SFA and learn an SFA using SAI a part of the sample, then test the learned SFA on the rest of the sample.
    
    """
    accuracies = np.zeros(nb_runs)
    learn_times = np.zeros(nb_runs)
    learn_samples = np.zeros(nb_runs)
    for i in range(nb_runs):
        testautomaton = generate_sfa(nb_states)

        start_time = time.time()
        sample = generate_random_sample(testautomaton, num_samples=nb_samples, stop_prob=stop_prob, mode=mode)
        sampling_time = time.time() - start_time
        learning_sample = set(list(sample)[:int(len(sample)*learning_part)])
        #print(learning_sample)
        testing_sample = sample - learning_sample
        learned_sfa = SAI(learning_sample).run_SAI()
        learning_time = time.time() - start_time - sampling_time
        if print_info:
            print(f"Learned SFA has {len(learned_sfa.states)} states.")
            print(f"Sampling time: {sampling_time}")
            print(f"Learning time: {learning_time}")
            visualize_automaton(testautomaton, path="./SAITesting/test_automaton_random_sample")
            visualize_automaton(learned_sfa, path="./SAITesting/learned_automaton_random_sample")
        correct = 0
        for word, label in testing_sample:
            if learned_sfa.accepts(word) == label:
                correct += 1
        accuracy = correct / len(testing_sample)
        if print_info:
            print(f"Accuracy: {correct}/{len(testing_sample)} = {correct/len(testing_sample):.2f}")
        accuracies[i] = accuracy
        learn_times[i] = learning_time
        learn_samples[i] = len(learning_sample)
    return accuracies, learn_times, learn_samples



def benchmark_random_sampling_vs_learning_part(
    learning_parts,
    nb_states=10,
    nb_runs=30,
    nb_samples=2000,
    stop_prob=0.1,
    mode=0,
    uncertainty="ci95",  # "ci95", "sem", "std"
    output_prefix="random_sampling_benchmark",
    print_info=False,
):
    mean_acc, err_acc = [], []
    all_times, all_learn_sizes, all_parts = [], [], []
    print(f"==Starting benchmark with nb_states={nb_states}, nb_runs={nb_runs}, nb_samples={nb_samples}, stop_prob={stop_prob}, mode={mode}==")
    for lp in learning_parts:
        print(f"Running benchmark for learning_part={lp:.2f}...")
        acc, learn_times, learn_samples = test_random_sampling(
            nb_states=nb_states,
            nb_runs=nb_runs,
            nb_samples=nb_samples,
            learning_part=lp,
            stop_prob=stop_prob,
            mode=mode,
            print_info=print_info,
        )

        # 1) accuracy vs learning_part
        m = float(np.mean(acc))
        s = float(np.std(acc, ddof=1)) if len(acc) > 1 else 0.0
        sem = s / np.sqrt(len(acc)) if len(acc) > 0 else 0.0

        if uncertainty == "std":
            e = s
        elif uncertainty == "sem":
            e = sem
        else:
            e = 1.96 * sem  # ci95

        mean_acc.append(m)
        err_acc.append(e)

        # 2) learning time vs learning sample size (raw points)
        all_times.extend(learn_times.tolist())
        all_learn_sizes.extend(learn_samples.tolist())
        all_parts.extend([lp] * len(learn_times))
        print(f"learning_part={lp:.2f}: mean_acc={m:.4f}, err_acc={e:.4f}, mean_time={np.mean(learn_times):.2f}s")

    plot_accuracy_vs_learning_part(
        learning_parts=learning_parts,
        mean_acc=mean_acc,
        err_acc=err_acc,
        output_path=f"{output_prefix}_accuracy_vs_learning_part.png",
        uncertainty=uncertainty,
        nb_runs=nb_runs,
    )

    plot_learning_time_vs_learning_sample_size(
        learn_sample_sizes=all_learn_sizes,
        learn_times=all_times,
        output_path=f"{output_prefix}_time_vs_learning_sample_size.png",
        log_scale=True,
    )

    # Optional extra plot: color by learning_part
    plot_time_vs_size_colored_by_learning_part(
        learn_sample_sizes=all_learn_sizes,
        learn_times=all_times,
        learning_parts=all_parts,
        output_path=f"{output_prefix}_time_vs_size_colored_by_part.png",
        log_scale=True,
    )


def plot_accuracy_vs_learning_part(
    learning_parts,
    mean_acc,
    err_acc,
    output_path="accuracy_vs_learning_part.png",
    uncertainty="ci95",
    nb_runs=30,
):
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.errorbar(
        learning_parts,
        mean_acc,
        yerr=err_acc,
        fmt="o-",
        color="tab:blue",
        capsize=4,
        elinewidth=1,
    )
    ax.set_xlabel("learning_part")
    ax.set_ylabel("Accuracy")
    ax.set_title(f"Accuracy vs learning_part ({uncertainty}, {nb_runs} runs)")
    ax.set_ylim(0.0, 1.02)
    ax.grid(True, alpha=0.3)
    fig.tight_layout()
    fig.savefig(output_path, dpi=200, bbox_inches="tight")
    plt.close(fig)
    print(f"Plot saved to: {output_path}")


def plot_learning_time_vs_learning_sample_size(
    learn_sample_sizes,
    learn_times,
    output_path="time_vs_learning_sample_size.png",
    log_scale=True,
):
    x = np.asarray(learn_sample_sizes, dtype=float)
    y = np.asarray(learn_times, dtype=float)

    if len(x) == 0:
        print("No data to plot for learning time vs learning sample size.")
        return

    fig, ax = plt.subplots(figsize=(7, 5))
    ax.scatter(x, y, alpha=0.6, s=24, color="tab:red", label="Runs")

    if log_scale:
        ax.set_xscale("log")
        ax.set_yscale("log")
        mask = (x > 0) & (y > 0)
        xf, yf = x[mask], y[mask]
        if len(xf) >= 2:
            lx, ly = np.log10(xf), np.log10(yf)
            k, b = np.polyfit(lx, ly, 1)
            C = 10 ** b
            x_fit = np.linspace(xf.min(), xf.max(), 300)
            y_fit = C * (x_fit ** k)
            ax.plot(x_fit, y_fit, color="tab:orange", lw=2, label=f"Fit: t ≈ {C:.2e}·n^{k:.2f}")

    ax.set_xlabel("Learning sample size (#words)")
    ax.set_ylabel("Learning time (s)")
    ax.set_title("Learning time vs learning sample size" + (" (log-log)" if log_scale else ""))
    ax.grid(True, alpha=0.25)
    ax.legend(loc="best")
    fig.tight_layout()
    fig.savefig(output_path, dpi=200, bbox_inches="tight")
    plt.close(fig)
    print(f"Plot saved to: {output_path}")


def plot_time_vs_size_colored_by_learning_part(
    learn_sample_sizes,
    learn_times,
    learning_parts,
    output_path="time_vs_size_colored_by_part.png",
    log_scale=True,
):
    x = np.asarray(learn_sample_sizes, dtype=float)
    y = np.asarray(learn_times, dtype=float)
    c = np.asarray(learning_parts, dtype=float)

    fig, ax = plt.subplots(figsize=(7, 5))
    sc = ax.scatter(x, y, c=c, cmap="viridis", alpha=0.7, s=28)
    cbar = fig.colorbar(sc, ax=ax)
    cbar.set_label("learning_part")

    if log_scale:
        ax.set_xscale("log")
        ax.set_yscale("log")

    ax.set_xlabel("Learning sample size (#words)")
    ax.set_ylabel("Learning time (s)")
    ax.set_title("Learning time vs learning sample size (colored by learning_part)")
    ax.grid(True, alpha=0.25)
    fig.tight_layout()
    fig.savefig(output_path, dpi=200, bbox_inches="tight")
    plt.close(fig)
    print(f"Plot saved to: {output_path}")

if __name__ == "__main__":
    parts = np.linspace(0.1, 0.9, 12)
    benchmark_random_sampling_vs_learning_part(
        learning_parts=parts,
        nb_states=12,
        nb_runs=5,
        nb_samples=2000,
        stop_prob=0.1,
        mode=0,
        uncertainty="ci95",
        output_prefix="random_sampling_sai",
    )