from aalpy.automata.Sfa import Sfa, SfaState
from aalpy.automata import Dfa, DfaState
from aalpy.base.BooleanAlgebra import IntervalPredicate, Predicate, BooleanAlgebra, IntervalAlgebra, OrPredicate
import numpy as np

alg = IntervalAlgebra()

def generate_sfa(nb_states):
    states = []
    for i in range(nb_states):
        s = SfaState(f"q{i}", is_accepting=np.random.choice([True, False])) 
        states.append(s)
    for i in range(nb_states):
        s = states[i]
        nb_trans = np.random.randint(nb_states//4, nb_states)
        bounds = sorted(np.random.choice(range(0, nb_trans*200), max(0, nb_trans-1), replace=False))
        bounds.append(None)
        for i, b in enumerate(bounds):
            pred = IntervalPredicate(int(bounds[i-1]) if i > 0 else None, int(b) if b is not None else None)
            target = np.random.choice(states)
            s.transitions.append((pred, target))
    s0 = states[0]
    sfa = Sfa(s0, states)
    return sfa

def sfa_to_dfa(sfa: Sfa) -> Dfa:
    """
    Transform an SFA into a Dfa using the lower bounds of the Intervals as input symbols.
    """
    state_mapping = {}
    for sfa_state in sfa.states:
        dfa_state = DfaState(sfa_state.state_id, is_accepting=sfa_state.is_accepting)
        state_mapping[sfa_state] = dfa_state
    
    for sfa_state in sfa.states:
        dfa_state = state_mapping[sfa_state]
        for predicate, target_sfa_state in sfa_state.transitions:
            assert isinstance(predicate, IntervalPredicate), "Expected Interval in SFA transitions"
            dfa_state.transitions[alg.pick_witness(predicate)] = state_mapping[target_sfa_state]


    return Dfa(state_mapping[sfa.initial_state], list(state_mapping.values()))
def dfa_to_sfa(dfa: Dfa, algebra: BooleanAlgebra) -> Sfa:
    """
    Transform a Dfa into an SFA by creating IntervalPredicates for each transition. The intervals are defined as gaps between the input symbols of the Dfa transitions

    for example, if a Dfa state has transitions on input symbols 1, 5, and 10, the corresponding SFA state will have transitions with predicates [1, 5), [5, 10), and [10, None) respectively.
    """
    assert all((lambda i: isinstance(i, int) or i == None) for s in dfa.states for i in s.transitions.keys()), "Expected integer inputs in Dfa transitions"
    dfa.make_input_complete()
    state_mapping = {}
    for dfa_state in dfa.states:
        sfa_state = SfaState(dfa_state.state_id, is_accepting=dfa_state.is_accepting)
        state_mapping[dfa_state] = sfa_state
    
    for dfa_state in dfa.states:
    

        sfa_state = state_mapping[dfa_state]
        # Sort the input symbols to create intervals
        sorted_inputs = sorted(dfa_state.transitions.keys(), key=lambda x: (float('-inf') if x is None else x))
        #make transitions with intervals
        for i, input_symbol in enumerate(sorted_inputs):
            next_input_symbol = sorted_inputs[i + 1] if i + 1 < len(sorted_inputs) else None
            target_dfa_state = dfa_state.transitions[input_symbol]
            if i == 0 and input_symbol is not None:
                # add transition for (-inf, first_input)
                predicate = IntervalPredicate(None, next_input_symbol)
                sfa_state.transitions.append((predicate, state_mapping[target_dfa_state]))
                continue
            predicate = IntervalPredicate(input_symbol, next_input_symbol)
            sfa_state.transitions.append((predicate, state_mapping[target_dfa_state]))

    return Sfa(state_mapping[dfa.initial_state], list(state_mapping.values()), algebra=algebra)


def generate_random_sample(sfa: Sfa, num_samples: int, stop_prob: float, mode:int) -> set:
    """
    Generate a random sample of words accepted or rejected.
    The sample is generated by performing random walks on the SFA. The walk starts from the initial state.
    The walk can stop with a probability of `stop_prob` at each step.
    at each step the next transition is chosen :
    - Mode 0: uniformly at random among the available transitions.
    - Mode 1: with a probability proportional to the size of the interval of the transition predicate.
    - Mode 2: according to a letter picked by a normal distribution such that there is an 80% chance it is between the lowest bound and highest bound of intervals of the outgoing transitions
    """
    assert mode in [0, 1,2], "Mode should be either 0, 1 or 2."
    assert 0 < stop_prob <= 1, "stop_prob should be between 0 and 1."
    sample = set()
    for _ in range(num_samples):
        sfa.current_state = sfa.initial_state
        word = []
        while True:
            if np.random.rand() < stop_prob:
                break
            if mode == 0:
                # uniform random choice among available transitions
                if not sfa.current_state.transitions:
                    break
                predicate, next_state = sfa.current_state.transitions[np.random.randint(len(sfa.current_state.transitions))]
                next_letter = sfa.algebra.pick_witness_random(predicate)                
            elif mode == 1:
                # probability proportional to the size of the interval, and force probability 0.1 for unbounded intervals
                if not sfa.current_state.transitions:
                    break
                sizes = [] 
                for pred, _ in sfa.current_state.transitions:
                    if isinstance(pred, IntervalPredicate) and sfa.algebra.is_satisfiable(pred):
                        if pred.lower is None or pred.upper is None:
                            sizes.append(-1)  # unbounded interval
                        else:  
                            sizes.append(pred.upper - pred.lower)
                    elif isinstance(pred, IntervalPredicate):
                        sizes.append(0)  # unsatisfiable interval
                    else:
                        print(f"Warning: non-interval predicate {pred} encountered.")
                        sizes.append(1)
                total_size = sum(size for size in sizes if size > 0)
                if total_size == 0:
                    probabilities = [1 / len(sfa.current_state.transitions)] * len(sfa.current_state.transitions)
                else:
                    for i in range(len(sizes)):
                        if sizes[i] == -1:  # unbounded interval
                            sizes[i] = 0.1 * total_size
                    
                    probabilities = [size / sum(sizes) for size in sizes]

                id = np.random.choice(len(sfa.current_state.transitions), p=probabilities)
                predicate, next_state = sfa.current_state.transitions[id]
                next_letter = sfa.algebra.pick_witness_random(predicate)
            elif mode == 2:
                lowest_bound = None
                highest_bound = None
                for pred, _ in sfa.current_state.transitions:
                    if isinstance(pred, IntervalPredicate):
                        if sfa.algebra.is_satisfiable(pred):
                            if lowest_bound is None or (pred.lower is not None and pred.lower < lowest_bound):
                                lowest_bound = pred.lower
                            if highest_bound is None or (pred.upper is not None and pred.upper > highest_bound):
                                highest_bound = pred.upper
                if lowest_bound is None:
                    lowest_bound = 0
                if highest_bound is None:
                    highest_bound = 1000
                #normal distibution so that 80% of the values are between lowest_bound and highest_bound
                mean = (lowest_bound + highest_bound) / 2
                std = (highest_bound - lowest_bound) / 2 / 0.84
                next_letter = int(np.random.normal(mean, std))
                
                next_state = sfa.current_state
            if next_letter is None:
                print(f"Warning: could not pick a witness for predicate {predicate}. Skipping this transition.")
                break
            word.append(next_letter)
            sfa.step(next_letter)

        sample.add((tuple(word), sfa.current_state.is_accepting))
    return sample

if __name__ == "__main__":
    from test_sai_characteristic import generate_sfa
    testautomaton = generate_sfa(3)
    sample = generate_random_sample(testautomaton, 10, 0.5, mode=2)
    print(sample)